services:
  answer-rest-service:
    container_name: "answer-service"
    build: .
    environment:
      HTTP_PORT: 8080
      LOGGER_LEVEL: "debug"
      LOGGER_DEVELOPMENT: "true"
      LOGGER_ENCODING: "json"
      LOGGER_ENCODER_CONFIG_MESSAGE_KEY: "message"
      LOGGER_ENCODER_CONFIG_LEVEL_KEY: "level"
      LOGGER_ENCODER_CONFIG_TIME_KEY: "time"
      LOGGER_ENCODER_CONFIG_NAME_KEY: "name"
      LOGGER_ENCODER_CONFIG_CALLER_KEY: "caller"
      LOGGER_ENCODER_CONFIG_FUNCTION_KEY: "function"
      LOGGER_ENCODER_CONFIG_STACKTRACE_KEY: "stacktrace"
      LOGGER_STDOUT_PATH: "stdout"
      LOGGER_STDERR_PATH: "stdout"
      DATABASE_USER: "user1"
      DATABASE_PASSWORD: "pass1"
      DATABASE_HOST: "answer-database"
      DATABASE_PORT: 5432
      DATABASE_NAME: "postgres"
      DATABASE_SSL_MODE: "disable"
    networks:
      - "answer-network"
    depends_on:
      - "answer-postgresql"
    ports:
      - "8080:8080"
  answer-postgresql:
    container_name: "answer-database"
    image: postgres:14
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "pass1"
    networks:
      - "answer-network"
    expose:
      - 5432
    ports:
      - "5432:5432"
networks:
  answer-network:
    name: "answer-network"
    driver: "bridge"
