// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	AnswerEvent string
	AnswerMap   string
}{
	AnswerEvent: "answer_event",
	AnswerMap:   "answer_map",
}
